# Generated by Django 5.1.1 on 2024-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0002_rename_roll_no_alert_message_m_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message_m',
            name='age',
            field=models.CharField(choices=[('Under 19', 'Under 19'), ('19 or Older', '19 or Older')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(choices=[('Development', 'Development'), ('Business', 'Business'), ('Design', 'Design')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='job_role',
            field=models.CharField(choices=[('Django Developer', 'Django Developer'), ('Python Developer', 'Python Developer'), ('Android Developer', 'Android Developer'), ('PHP Developer', 'PHP Developer'), ('Business Owner', 'Business Owner'), ('Mobile Designer', 'Mobile Designer'), ('iOS Developer', 'iOS Developer'), ('Web Designer', 'Web Designer'), ('WordPress Developer', 'WordPress Developer'), ('Front-End Developer', 'Front-End Developer'), ('Freelancer', 'Freelancer')], max_length=150),
        ),
    ]
