# Generated by Django 5.1.1 on 2024-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0003_alter_alert_message_m_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message_m',
            name='age',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='job_role',
            field=models.CharField(max_length=150),
        ),
    ]
