# Generated by Django 5.1.1 on 2024-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0004_alter_alert_message_m_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message_m',
            name='age',
            field=models.CharField(choices=[('Under 19', 'Under 19'), ('19 or Older', '19 or Older')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(choices=[('Business', 'Business'), ('Design', 'Design'), ('Development', 'Development')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='job_role',
            field=models.CharField(choices=[('WordPress Developer', 'WordPress Developer'), ('Freelancer', 'Freelancer'), ('iOS Developer', 'iOS Developer'), ('Web Designer', 'Web Designer'), ('Django Developer', 'Django Developer'), ('Android Developer', 'Android Developer'), ('Python Developer', 'Python Developer'), ('Mobile Designer', 'Mobile Designer'), ('Front-End Developer', 'Front-End Developer'), ('PHP Developer', 'PHP Developer'), ('Business Owner', 'Business Owner')], max_length=150),
        ),
    ]
