# Generated by Django 5.1.1 on 2024-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0005_alter_alert_message_m_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_message_m',
            name='job_role',
        ),
        migrations.AddField(
            model_name='alert_message_m',
            name='course_name',
            field=models.CharField(choices=[('PHP Developer', 'PHP Developer'), ('WordPress Developer', 'WordPress Developer'), ('Mobile Designer', 'Mobile Designer'), ('Freelancer', 'Freelancer'), ('Business Owner', 'Business Owner'), ('Web Designer', 'Web Designer'), ('Django Developer', 'Django Developer'), ('iOS Developer', 'iOS Developer'), ('Python Developer', 'Python Developer'), ('Android Developer', 'Android Developer'), ('Front-End Developer', 'Front-End Developer')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='age',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(choices=[('Design', 'Design'), ('Business', 'Business'), ('Development', 'Development')], max_length=150),
        ),
    ]
