# Generated by Django 5.1.1 on 2024-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0006_remove_alert_message_m_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message_m',
            name='course_name',
            field=models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Office Management', 'Office Management'), ('Grapics Design', 'Grapics Design'), ('Web Development (Django)', 'Web Development (Django)'), ('Django Developer', 'Django Developer'), ('Python Programming', 'Python Programming')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(choices=[('Business', 'Business'), ('Design', 'Design'), ('Development', 'Development')], max_length=150),
        ),
    ]
