# Generated by Django 5.1.1 on 2024-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0009_alter_alert_message_m_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_message_m',
            name='course_name',
            field=models.CharField(choices=[('Grapics Design', 'Grapics Design'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Python Programming', 'Python Programming'), ('Digital Marketing', 'Digital Marketing'), ('Web Development (Django)', 'Web Development (Django)'), ('Office Management', 'Office Management')], max_length=150),
        ),
        migrations.AlterField(
            model_name='alert_message_m',
            name='interest',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('Marketing', 'Marketing')], max_length=150),
        ),
    ]
