# Generated by Django 5.1.1 on 2024-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0010_alter_alert_message_m_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftTech_Student_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('biography', models.CharField(max_length=200)),
                ('course_name', models.CharField(choices=[('Web Development (Django)', 'Web Development (Django)'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Office Management', 'Office Management'), ('Grapics Design', 'Grapics Design'), ('Digital Marketing', 'Digital Marketing'), ('Python Programming', 'Python Programming')], max_length=150)),
                ('interest', models.CharField(choices=[('Design', 'Design'), ('Marketing', 'Marketing'), ('Development', 'Development')], max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='alert_message_m',
        ),
    ]
