# Generated by Django 5.1.1 on 2024-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canava', '0012_alter_softtech_student_id_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softtech_student_id',
            name='course_name',
            field=models.CharField(choices=[('Grapics Design', 'Grapics Design'), ('Python Programming', 'Python Programming'), ('Web Development (Django)', 'Web Development (Django)'), ('Digital Marketing', 'Digital Marketing'), ('Web Development (Python,Django)', 'Web Development (Python,Django)'), ('Office Management', 'Office Management')], max_length=150),
        ),
        migrations.AlterField(
            model_name='softtech_student_id',
            name='interest',
            field=models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Marketing', 'Marketing')], max_length=150),
        ),
    ]
